### ISSUE TITLE
Routing Issues and unwanted URL Parameters

### ISSUE THREAD

**Issue by pixelbreit** [pegasuswerbeagentur/google_for_jobs#16]
First of all, my compliments for the great extension.

But I have the following problem (google_for_jobs 2.1, TYPO3 10.4.18, PHP 7.2). 
On all pages with the list view plugin, parameters are automatically appended to the URLs. 
They look like this 
https://www.mydomain.de/karriere/stellenangebote?tx_googleforjobs_job[action]=listSelected&tx_googleforjobs_job[controller]=Job&cHash=105f0d079ba8b884872de3430df4d555
but should be:
https://www.mydomain.de/karriere/stellenangebote/

I added the following routeEnhancer to my config.yaml: 
```
routeEnhancers:
  JobsPlugin:
    type: Extbase
    extension: GoogleForJobs
    plugin: Job
    routes:
      -
        routePath: '/{job-title}'
        _controller: 'Job::show'
        _arguments:
          job-title: job
    defaultController: 'Job::show' _arguments
    aspects:
      job-title:
        type: PersistedAliasMapper
        tableName: tx_googleforjobs_domain_model_job
        routeFieldName: path_segment
```
The links to the detail page are generated and working correctly. 
Only the pages with the list views should not have anything appended to the URL.

What could be the reason for this?
Have I done something wrong?
